//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeBetterApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sk-proj-YpGbl5MOX4v4jnls6ZB5CcT31bIMHLSr72WQKd4zPptRYVBwXqNaXBGDKzbYfd1qZrWp8olsD" +
            "MT3BlbkFJ4RX3fBonqsMg3roQYrt-4ApqQ64bgGP-z_b0fYUM6DMPAja57jA9-hQni-Wg8Xvzf3VwTg7" +
            "fQA")]
        public string OPENAI_KEY {
            get {
                return ((string)(this["OPENAI_KEY"]));
            }
        }
    }
}
